#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'HELP'
Uptime LoFi probe installer

Required environment variables:
  UPTIME_PROBE_PUSH_URL  Dashboard probe push endpoint, usually https://.../api/push
  UPTIME_MONITOR_ID      Monitor identifier generated by the dashboard
  UPTIME_MONITOR_SECRET  Monitor-specific credential generated by the dashboard
  UPTIME_PLATFORM        Release platform: linux/amd64, linux/arm64, darwin/amd64, darwin/arm64

Optional environment variables:
  UPTIME_INSTALL_DIR     Install directory, defaults to $HOME/.uptime-lofi
  UPTIME_RELEASE_REPO    GitHub repository slug, defaults to zardonc/uptime-lofi
  UPTIME_RELEASE_TAG     GitHub release tag, defaults to probe-latest

Example:
  UPTIME_PLATFORM='linux/amd64' UPTIME_PROBE_PUSH_URL='https://example/api/push' UPTIME_MONITOR_ID='monitor' UPTIME_MONITOR_SECRET='secret' bash scripts/install-probe.sh
HELP
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  usage
  exit 0
fi

require_env() {
  local name="$1"
  if [ -z "${!name:-}" ]; then
    printf 'Missing required environment variable: %s\n\n' "$name" >&2
    usage >&2
    exit 1
  fi
}

require_env UPTIME_PROBE_PUSH_URL
require_env UPTIME_MONITOR_ID
require_env UPTIME_MONITOR_SECRET
require_env UPTIME_PLATFORM

case "$UPTIME_PLATFORM" in
  linux/amd64) asset="probe-linux-amd64.tar.gz" ;;
  linux/arm64) asset="probe-linux-arm64.tar.gz" ;;
  darwin/amd64) asset="probe-darwin-amd64.tar.gz" ;;
  darwin/arm64) asset="probe-darwin-arm64.tar.gz" ;;
  *)
    printf 'Unsupported UPTIME_PLATFORM: %s\n' "$UPTIME_PLATFORM" >&2
    exit 1
    ;;
esac

install_dir="${UPTIME_INSTALL_DIR:-$HOME/.uptime-lofi}"
release_repo="${UPTIME_RELEASE_REPO:-zardonc/uptime-lofi}"
release_tag="${UPTIME_RELEASE_TAG:-probe-latest}"
download_url="https://github.com/${release_repo}/releases/download/${release_tag}/${asset}"
archive_path="${install_dir}/${asset}"

mkdir -p "$install_dir"

cat > "${install_dir}/config.yaml" <<CONFIG
api_url: ${UPTIME_PROBE_PUSH_URL}
monitor_id: ${UPTIME_MONITOR_ID}
psk: ${UPTIME_MONITOR_SECRET}
enable_docker: true
CONFIG

printf 'Downloading Uptime LoFi probe from %s\n' "$download_url"
if command -v curl >/dev/null 2>&1; then
  curl -fsSL "$download_url" -o "$archive_path"
elif command -v wget >/dev/null 2>&1; then
  wget -qO "$archive_path" "$download_url"
else
  printf 'Install curl or wget, then rerun this command.\n' >&2
  exit 1
fi

tar -xzf "$archive_path" -C "$install_dir"
probe_binary="${asset%.tar.gz}"
if [ ! -f "${install_dir}/${probe_binary}" ]; then
  printf 'Expected probe binary not found after extraction: %s\n' "${install_dir}/${probe_binary}" >&2
  exit 1
fi
chmod +x "${install_dir}/${probe_binary}"
ln -sf "${install_dir}/${probe_binary}" "${install_dir}/uptime-lofi-probe"

cat <<NEXT
Probe installed in ${install_dir}
Config written to ${install_dir}/config.yaml

Start it now with:
  cd ${install_dir} && ./uptime-lofi-probe --config config.yaml

For systemd, create a service that runs the same command from ${install_dir}.
NEXT
